//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccounting.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentBuild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentBuild()
        {
            this.Equipments = new HashSet<Equipments>();
        }
    
        public int InventoryNumber { get; set; }
        public int LocationID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Locations Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipments> Equipments { get; set; }

        public string GetSearchString() => $"{InventoryNumber}{Locations.Name}".ToLower();
    }
}
